build:
	gcc Client_string_4.c -o one -lrt
	gcc Server_string.c_4 -o two -lrt
	gcc stack.c_1 -o stack -lpthread
	gcc Stack_mutex.c_3 -o mutex -lpthread
	gcc sender2_5.c -o send2 -lrt
	gcc rec2_5.c -o rec2 -lrt
	gcc SharedMemory. -o shared -lrt
	gcc SemaphoreQueue_2.c -o Sema -lpthread
	gcc Mutexque.c -o mque -lpthread



